title: Jason Boyer # your name (or website title) here
logo: "/images/jblogo3.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Analyzing and visualizing data to better understand which decisions to make 
  <br><br>
  Python, VBA, Javascript, Tableau 
  <br><br>
  <a href="https://www.linkedin.com/in/jason-boyer7/">View My LinkedIn Profile</a> 
 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

