title: Jason Boyer # your name (or website title) here
logo: "/images/jblogo3.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description 
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/jason-boyer7/">View My LinkedIn Profile</a> 
  <br><br>
  <a "/images/Jason Boyer-RESUME-2021 (1).pdf">View My Resume</a>
 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

